### Load tensorflow

In [1]:
import tensorflow as tf

### Collect Data

https://www.kaggle.com/c/word2vec-nlp-tutorial/data

In [2]:
import pandas as pd

In [3]:
#Read file into pandas dataframe
df = pd.read_csv('labeledTrainData.tsv.zip',header=0, delimiter="\t", quoting=3)

print('Number of examples: ', df.shape)
df.head()

Number of examples:  (25000, 3)


id  sentiment                                             review
0  "5814_8"          1  "With all this stuff going down at the moment ...
1  "2381_9"          1  "\"The Classic War of the Worlds\" by Timothy ...
2  "7759_3"          0  "The film starts with a manager (Nicholas Bell...
3  "3630_4"          0  "It must be assumed that those who praised thi...
4  "9495_8"          1  "Superbly trashy and wondrously unpretentious ...

In [4]:
df.review[0]

'"With all this stuff going down at the moment with MJ i\'ve started listening to his music, watching the odd documentary here and there, watched The Wiz and watched Moonwalker again. Maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent. Moonwalker is part biography, part feature film which i remember going to see at the cinema when it was originally released. Some of it has subtle messages about MJ\'s feeling towards the press and also the obvious message of drugs are bad m\'kay.<br /><br />Visually impressive but of course this is all about Michael Jackson so unless you remotely like MJ in anyway then you are going to hate this and find it boring. Some may call MJ an egotist for consenting to the making of this movie BUT MJ and most of his fans would say that he made it for the fans which if true is really nice of him.<br /><br />The actual feature film bit when it finally

In [5]:
#Extract review and sentiments
reviews = df['review'].tolist()
sentiment = df['sentiment'].tolist()


### Convert Text Into numbers

#### Build Keras Tokenizer

In [6]:
#Initialize Tokenizer
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=5000)

#Let tokenizer look at all the text
tokenizer.fit_on_texts(reviews)

In [7]:
#Vocablury
len(tokenizer.word_index)

88582


#### Convert Text Into numbers using TF-IDF

In [8]:
#Convert text into numbers
features = tokenizer.texts_to_matrix(reviews, mode='tfidf')

In [9]:
#Input data shape
features.shape

(25000, 5000)

In [10]:
features[0]

array([0.        , 2.75042893, 2.34574918, ..., 0.        , 0.        ,
       0.        ])

### Build the Graph

In [11]:
#Initialize model, reshape & normalize data
model = tf.keras.models.Sequential()

#normalize data
model.add(tf.keras.layers.BatchNormalization(input_shape=(5000,)))

#Add Dense Layers
model.add(tf.keras.layers.Dense(200, activation='relu'))
model.add(tf.keras.layers.Dense(100, activation='relu'))
model.add(tf.keras.layers.Dense(60, activation='relu'))
model.add(tf.keras.layers.Dense(30, activation='relu'))

### Build the Graph...

In [12]:
#Output layer
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

In [13]:
#Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

## Train the model

In [ ]:
#Train the model
model.fit(features,sentiment,          
          validation_split=0.2,
          callbacks=[tensorboard],
          epochs=10,
          batch_size=32)

Train on 20000 samples, validate on 5000 samples
Instructions for updating:
Use tf.cast instead.
Epoch 1/10
20000/20000 [==============================] - 15s 739us/sample - loss: 0.5462 - acc: 0.8069 - val_loss: 0.5198 - val_acc: 0.8096
Epoch 2/10
20000/20000 [==============================] - 14s 704us/sample - loss: 0.4505 - acc: 0.8714 - val_loss: 0.4478 - val_acc: 0.8506
Epoch 3/10
20000/20000 [==============================] - 14s 705us/sample - loss: 0.3802 - acc: 0.9001 - val_loss: 0.4178 - val_acc: 0.8524
Epoch 4/10
20000/20000 [==============================] - 14s 701us/sample - loss: 0.3266 - acc: 0.9175 - val_loss: 0.3909 - val_acc: 0.8632
Epoch 5/10
20000/20000 [==============================] - 14s 705us/sample - loss: 0.2760 - acc: 0.9355 - val_loss: 0.4014 - val_acc: 0.8492
Epoch 6/10
20000/20000 [==============================] - 14s 707us/sample - loss: 0.2314 - acc: 0.9497 - val_loss: 0.3964 - val_acc: 0.8496
Epoch 7/10
20000/20000 [==============================] -

In [ ]:
model.predict(features[0:1])

array([[0.95040756]], dtype=float32)

In [ ]:
a = 'Vey nice xyz'
a_f = tokenizer.texts_to_matrix([a], mode='tfidf')

In [ ]:
a_f.shape

(1, 5000)

In [ ]:
model.predict(a_f)

array([[0.77600497]], dtype=float32)